name: Test PR

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create production properties file
        uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: '{'
          tokenSuffix: '}'
          files: '["**/*.properties"]'
        env:
          DB_URL: ${{ secrets.DB_URL }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean package

      - name: Generate encrypted deployment artifact.
        run: zip --password ${{ secrets.ARTIFACT_PASSWORD }} -r deploy.zip . -x '*.git*'

      - name: Upload artifact for testing
        uses: actions/upload-artifact@v4
        with:
          name: deploy.zip
          path: deploy.zip        